version: "3"

services:
  app:
    build: .
    command: yarn server
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CRUD
    volumes:
      - ./pgdata:/usr/postgresql/data
    ports:
      - "5432:5432"
